model: "ARCroco3DStereo(
  ARCroco3DStereoConfig(
    freeze='cut3r_wo_rgb', state_size=768, state_pe='2d', pos_embed='RoPE100', rgb_head=True, pose_head=True, patch_embed_cls='ManyAR_PatchEmbed',
    img_size=(512, 512), head_type='dpt', output_mode='gaussian', depth_mode=('exp', -inf, inf),
    conf_mode=('exp', 1, inf), pose_mode=('exp', -inf, inf), enc_embed_dim=1024, enc_depth=24, enc_num_heads=16,
    dec_embed_dim=768, dec_depth=12, dec_num_heads=12, landscape_only=False,
    gaussian_adapter_cfg=GaussianAdapterCfg(gaussian_scale_max=0.3, sh_degree=3, scale_activation='exp', scale_factor_alpha=0.05, only_rest=False, predict_offset=True),
    gaussian_decoder_cfg=DecoderSplattingCUDACfg(name='splatting_cuda', background_color=[0.0, 0.0, 0.0], make_scale_invariant=False, near=0.01, far=100.0),
    use_gt_pose=True,
  )
  )"
pretrained: checkpoint-epoch_0_11934.pth
load_only_encoder: False
long_context: True
fixed_length: False
resume: null
benchmark: False
num_views : 64
num_test_views : 16
n_corres_train: 0
n_corres_test: 0

train_criterion: RenderLoss(MSE, shape="BHWC") + 0.1 * RenderLoss(LPIPS, shape="BCHW")
test_criterion: RenderLoss(MSE, shape="BHWC")

resolution: [(512, 384), (512, 336), (512, 288), (512, 256), (512, 208), (512, 144), (384, 512), (336, 512), (288, 512), (256, 512)]

allow_repeat: True
train_dataset: Waymo_Multi(allow_repeat=${allow_repeat}, split=None, ROOT="../data/processed_waymo/", img_ray_mask_p=[1.0, 0.0, 0.0], valid_camera_id_list=["1", "2", "3"], aug_crop=16, resolution=[(512, 384), (512, 336), (512, 288), (512, 256), (512, 208), (512, 144), (384, 512), (336, 512), (288, 512), (256, 512)], transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
test_dataset: 1000 @ Waymo_Multi(split=None, ROOT="../data/processed_waymo/", img_ray_mask_p=[1.0, 0.0, 0.0], valid_camera_id_list=["1", "2", "3"], resolution=(512, 384), num_views=${num_test_views}, seed=42, n_corres=${n_corres_test})

seed: 0
batch_size: 4
accum_iter: 4
gradient_checkpointing: True
epochs: 10
start_epoch: 0
weight_decay: 0.05
lr: 1e-5
min_lr: 1e-6
warmup_epochs: 0.005
amp: 1

num_workers: 4
world_size: 1
local-rank: -1
dist_url: 'env://'
rank: 0
gpu: 0
distributed: False
dist_backend: 'nccl'

eval_freq: 1
save_freq: 0.05
keep_freq: 1
print_freq: 10
print_img_freq: 50000000
num_imgs_vis: 4
save_dir: 'checkpoints/waymo'
exp_name: 'exp_0.05_0.3_w_offset_gt'
task: 'cut3r'
logdir: ./${save_dir}/${exp_name}/logs
output_dir: ./${save_dir}/${exp_name}/
hydra:
  verbose: True
  run:
    dir: ./${save_dir}/${exp_name}