# Stage 1 Online Training Configuration for VGGT
# 第一阶段在线训练配置 - 包含统一的损失权重管理

# debug: True

# =============== 模型配置 ===============
model: "VGGT(img_size=518, patch_size=14, embed_dim=1024)"
pretrained: model.pt

# VGGT冻结策略配置
# 可选值: "none", "encoder", "encoder_frame", "backbone", "backbone_camera", "backbone_pts",
#        "vggt", "vggt_wo_velocity", "vggt_wo_depth", "vggt_wo_gaussian_and_velocity", "all", "old"
# null表示不设置冻结策略（保持模型默认行为）
vggt_freeze_strategy: "old"


# =============== 辅助模型配置 ===============
auxiliary_models:
  # 光流模型 (用于flow_loss)
  flow: RAFT(RAFTCfg(name="kitti-M", dataset="kitti", path="Tartan-C-T-TSKH-kitti432x960-M.pth",
    use_var=True, var_min=0, var_max=10, pretrain="resnet34", initial_dim=64, block_dims=[64, 128, 256],
    radius=4, dim=128, num_blocks=2, iters=4, image_size=[432, 960],
    offload=${offload_auxiliary}, geo_thresh=2, photo_thresh=-1))

  # SAM2模型 (用于velocity consistency loss)
  # sam2: SAM2Base(config_file="sam2.1_hiera_t", path="sam2.1_hiera_tiny.pt",
  #   offload=${offload_auxiliary})

  # DAM2模型 (用于生成sky masks)
  dam2: DepthAnythingV2(encoder="vitb", offload=${offload_auxiliary})

  # VGGT teacher模型 (用于渲染损失)
  # vggt_teacher: VGGT(path="/mnt/teams/algo-teams/yuxue.yang/4DVideo/ziqi/4DVideo/src/model.pt", offload=${offload_auxiliary})

offload_auxiliary: False

# =============== 训练配置 ===============
load_only_encoder: False
long_context: True
fixed_length: False
resume: null
benchmark: False
num_views: 8
num_test_views: 16
n_corres_train: 0
n_corres_test: 0

# =============== 训练阶段配置 ===============
# 'stage1': 第一阶段训练 - 训练VGGT主模型的gaussian head, velocity head等
# 'stage2': 第二阶段训练 - 只训练refine模型，包含渲染损失
# 'joint': 联合训练模式 - 同时训练两个阶段（实验性）
training_stage: 'stage1'

# =============== 第一阶段损失权重配置 ===============
# 权重为0则完全不计算该损失

# 1. Self Render Loss (训练gaussian head)
self_render_weight: 1.0                    # Gaussian参数学习的主要损失 (已弃用，使用下面的分项权重)
self_render_rgb_weight: 1.0                # RGB损失权重
self_render_lpips_weight: 0.1              # LPIPS感知损失权重
self_render_depth_weight: 1.0              # 深度损失权重

# 2. Flow Loss (训练velocity head)
flow_loss_weight: 0.5                      # 光流监督velocity学习
flow_interval: 1                           # 光流计算的帧间隔

# 3. SAM2 Velocity Consistency Loss (辅助velocity head监督)
sam2_velocity_weight: 0.0                  # SAM2掩码一致性监督
use_preprocessed_sam: false                 # false=在线推理SAM2, true=使用预处理掩码

# 4. Sky Opacity Loss (监督gaussian head的opacity参数)
sky_opacity_weight: 0.2                    # 天空区域opacity约束

# 5. Sky Color Loss (监督sky token以及sky head学习)
sky_color_weight: 0.0                      # 天空颜色预测监督 (已融合到self_render_loss中)

# 6. Velocity Regularization Loss (约束velocity值)
velocity_reg_weight: 0.01               # 速度正则化约束

# 7. VGGT Distillation Loss (蒸馏损失，监督depth head、camera head等)
vggt_distill_weight: 0.0                   # VGGT teacher蒸馏监督，防止unfreeze backbone时输出漂移

# =============== 数据集配置 ===============

allow_repeat: False

train_dataset: Waymo_Multi(allow_repeat=${allow_repeat}, split=None,
  ROOT="/mnt/teams/algo-teams/yuxue.yang/4DVideo/preprocessed_dataset/waymo/train",
  img_ray_mask_p=[1.0, 0.0, 0.0], valid_camera_id_list=["1", "2", "3"],
  aug_crop=0, resolution=[(518, 378),(518, 336),(518, 294),(518, 252),(518, 210),(518, 140),(378, 518),(336, 518),(294, 518),(252, 518)], transform=ImgNorm,
  num_views=${num_views}, n_corres=${n_corres_train}, seq_aug_crop=True, load_sam_masks=False)

test_dataset: 1000 @ Waymo_Multi(split=None,
  ROOT="/mnt/teams/algo-teams/yuxue.yang/4DVideo/preprocessed_dataset/waymo/train",
  img_ray_mask_p=[1.0, 0.0, 0.0], valid_camera_id_list=["1", "2", "3"],
  resolution=[(518, 378),(518, 336),(518, 294),(518, 252),(518, 210),(518, 140),(378, 518),(336, 518),(294, 518),(252, 518)], num_views=${num_test_views}, seed=42, n_corres=${n_corres_test})

# =============== 优化器配置 ===============
seed: 0
batch_size: 1
accum_iter: 4
gradient_checkpointing: True
epochs: 10
start_epoch: 0
weight_decay: 0.05
lr: 3e-5
min_lr: 1e-8
warmup_epochs: 0.005
amp: 1

# =============== 训练监控配置 ===============
num_workers: 4
world_size: 1
local-rank: -1
dist_url: 'env://'
rank: 0
gpu: 0
distributed: False
dist_backend: 'nccl'

eval_freq: 1
save_freq: 0.05                             # 每10%的epoch保存一次
keep_freq: 2
print_freq: 10
print_img_freq: 50000000
num_imgs_vis: 4

# =============== 输出配置 ===============
save_dir: 'checkpoints/waymo_stage1_online_debug'
exp_name: 'stage1_online'
task: 'cut3r'
logdir: ./${save_dir}/${exp_name}/logs
output_dir: ./${save_dir}/${exp_name}/

# =============== 第二阶段配置 (禁用) ===============
# 第一阶段训练时禁用第二阶段
enable_stage2: false
stage2_start_epoch: 999                    # 设置很大的值以禁用
stage2_frequency: 999

# =============== Hydra配置 ===============
hydra:
  verbose: True
  run:
    dir: ./${save_dir}/${exp_name}