# ICP数据收集配置 - 基于stage2_online.yaml简化版
# 只保留必要的配置用于模型推理和数据收集

# =============== 模型配置 ===============
model: "VGGT(img_size=518, patch_size=14, embed_dim=1024)"
pretrained_velocity: "/mnt/teams/algo-teams/yuxue.yang/4DVideo/ziqi/4DVideo/src/checkpoints/waymo_stage1_online/aggregator_resume_noflowgrad_nearestdynamic_resume_0point1_novoxel/checkpoint-epoch_0_45568.pth"

# =============== 数据集配置 ===============
train_dataset: Waymo_Multi(allow_repeat=False, split=None,
  ROOT="/mnt/teams/algo-teams/yuxue.yang/4DVideo/preprocessed_dataset/waymo/train_with_flow",
  img_ray_mask_p=[1.0, 0.0, 0.0], valid_camera_id_list=["1", "2", "3"],
  aug_crop=0, resolution=[(518, 378)], transform=ImgNorm,
  num_views=8, n_corres=0, seq_aug_crop=True, load_sam_masks=False)

# =============== 训练配置 ===============
batch_size: 1
num_workers: 4
fixed_length: False
gpu: 0

# =============== 动态处理器配置 ===============
min_object_size: 100
max_objects_per_frame: 10
velocity_threshold: 0.1
clustering_eps: 0.02
clustering_min_samples: 10
tracking_position_threshold: 2.0
tracking_velocity_threshold: 0.2
use_optical_flow_aggregation: true
use_velocity_based_transform: true

# =============== ICP数据收集配置 ===============
icp_max_batches: 10000
icp_data_dir: './icp_supervision_data_real'
icp_stage2_objects_dir: './stage2_dynamic_objects_collected'
use_color_features: true  # 是否启用颜色特征进行ICP配准
voxel_size: 0.1  # 体素大小，用于点云下采样
ransac_max_iteration: 500000  # RANSAC最大迭代次数
ransac_confidence: 500  # RANSAC置信度参数

# =============== 输出配置 ===============
exp_name: 'icp_data_collection'
output_dir: './icp_collection_temp'

# =============== Hydra配置 ===============
hydra:
  verbose: True
  run:
    dir: ./${output_dir}
