debug: True
model: "VGGT(img_size=518, patch_size=14, embed_dim=1024)"
pretrained: /mnt/teams/algo-teams/yuxue.yang/4DVideo/ziqi/4DVideo/src/checkpoints/waymo/step1/checkpoint-epoch_0_37191.pth

auxiliary_models:
  flow: RAFT(RAFTCfg(name="kitti-M", dataset="kitti", path="Tartan-C-T-TSKH-kitti432x960-M.pth",
    use_var=True, var_min=0, var_max=10, pretrain="resnet34", initial_dim=64, block_dims=[64, 128, 256],
    radius=4, dim=128, num_blocks=2, iters=4, image_size=[432, 960],
    offload=${offload_auxiliary}, geo_thresh=2, photo_thresh=-1))

offload_auxiliary: False
load_only_encoder: False
long_context: True
fixed_length: False
resume: null
benchmark: False
num_views : 4
num_test_views : 16
n_corres_train: 0
n_corres_test: 0

train_criterion: RenderLoss(MSE, shape="BHWC") + 0.1 * RenderLoss(LPIPS, shape="BCHW")
test_criterion: RenderLoss(MSE, shape="BHWC")

resolution: [(518, 378),(518, 336),(518, 294),(518, 252),(518, 210),(518, 140),(378, 518),(336, 518),(294, 518),(252, 518)]

allow_repeat: True
train_dataset: Waymo_Multi(allow_repeat=${allow_repeat}, split=None, ROOT="/mnt/teams/algo-teams/yuxue.yang/4DVideo/preprocessed_dataset/waymo/train", img_ray_mask_p=[1.0, 0.0, 0.0], valid_camera_id_list=["1", "2", "3"], aug_crop=16, resolution=[(518, 378),(518, 336),(518, 294),(518, 252),(518, 210),(518, 140),(378, 518),(336, 518),(294, 518),(252, 518)], transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
test_dataset: 1000 @ Waymo_Multi(split=None, ROOT="/mnt/teams/algo-teams/yuxue.yang/4DVideo/preprocessed_dataset/waymo/train", img_ray_mask_p=[1.0, 0.0, 0.0], valid_camera_id_list=["1", "2", "3"], resolution=[(518, 378),(518, 336),(518, 294),(518, 252),(518, 210),(518, 140),(378, 518),(336, 518),(294, 518),(252, 518)], num_views=${num_test_views}, seed=42, n_corres=${n_corres_test})

seed: 0
batch_size: 1
accum_iter: 4
gradient_checkpointing: True
epochs: 10
start_epoch: 0
weight_decay: 0.05
lr: 3e-5
min_lr: 1e-8
warmup_epochs: 0.005
amp: 1

num_workers: 4
world_size: 1
local-rank: -1
dist_url: 'env://'
rank: 0
gpu: 0
distributed: False
dist_backend: 'nccl'

eval_freq: 1
save_freq: 0.02
keep_freq: 1
print_freq: 10
print_img_freq: 50000000
num_imgs_vis: 4
save_dir: 'checkpoints/waymo'
exp_name: 'step1'
task: 'cut3r'
logdir: ./${save_dir}/${exp_name}/logs
output_dir: ./${save_dir}/${exp_name}/
hydra:
  verbose: True
  run:
    dir: ./${save_dir}/${exp_name}